title: Alpha's blog
description: Alpha Diallo's personal blog
permalink: ':title/'
baseurl: ''
url: alphasldiallo.github.io
relative_url: https://alphasldiallo.github.io
author: Alpha Diallo
author-img: alpha-diallo.png
about-author: PhD candidate | Software Engineer
social-twitter: alphadl9
social-github: alphasldiallo
social-linkedin: alpha-diallo-09
social-email: alpha.diallo@unil.ch
discus-identifier: alphasldiallo
analytics: 'null'
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-admin
  - jekyll-seo-tag
paginate: 8
paginate_path: '/page/:num'
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
tagline: >-
  Personal website of Alpha Diallo dedicated to sharing some updates about my
  projects
