title: Alpha's blog
description: |
  I'm gonna do it later
permalink: ':title/'
baseurl: ''
url: alphasldiallo.github.io
site-twitter: alphadiallo009
author: Alpha Diallo
author-img: alpha-diallo.png
about-author: PhD student - Full stack developer
social-twitter: alphadiallo009
social-facebook: null
social-github: alphasldiallo
social-linkedin: alpha-diallo-09
social-email: alpha.diallo@unil.ch
discus-identifier: alphasldiallo
analytics: 'null'
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-admin
paginate: 8
paginate_path: '/page/:num'
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
